spring:
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 5000
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here}
  expiration: 86400000 # 24 hours

stripe:
  secretKey: ${STRIPE_SECRET_KEY:your-stripe-secret-key-here}
  publicKey: ${STRIPE_PUBLIC_KEY:your-stripe-public-key-here}

# Logging configuration
logging:
  level:
    root: INFO
    com.example.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE